"""Stage C0 subtasks C0.1-C0.4: freeze and report the adopted H2E hydrology.

    python3.10 src/report_h2e.py

WHY A SCRIPT AND NOT A NOTEBOOK CELL
------------------------------------
Notebook 14 is generated by `src/nbgen/make_nb14.py` and reports the two cells it was
pre-registered around (H1, H2) plus the stored Config B reference.  H2E was
pre-registered later (docs/29) and adopted later still (docs/30), so its report is a
separate, re-runnable step rather than an edit that would force a five-hour re-execution
of nb14 and rewrite artefacts H2E does not touch.  Every schema written here is taken
from make_nb14.py section 13 unchanged, and the decoder is REGRESSION-CHECKED against
the stored `parameters_H1.csv` / `parameters_H2.csv` before it is used on H2E (see
`check_decoder`) - so "same schema" is a measured claim, not an assertion.

ORDER IS LOAD-BEARING.  C0.2 (the reproduction gate) runs before anything is
interpreted or written to `sim_calibrated_v2/`, and a mismatch exits non-zero: docs/31
Stage C0 makes the gate block every other subtask.
"""
from __future__ import annotations

import hashlib
import json
import pathlib
import sys
import time

import numpy as np
import pandas as pd

REPO = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / 'src'))

import calib_v2 as CV  # noqa: E402

PROC = REPO / 'data' / 'processed'
CACHE = PROC / '_calib_cache'
OUTD = PROC / 'sim_calibrated_v2'

CELL_NAME = 'H2E'
BEST_SEED = 20260901                 # docs/29 read-out: F 0.25931 vs 0.24671 at 20260902
SEEDS = (20260901, 20260902)
F_ARCHIVED = 0.25930593639066796     # docs/31 s0 quotes this as 0.25931
GATE_REL = 1e-8                      # docs/22's established 9.1e-9 harness bar

# the seed nb14 reported for each of its own cells, needed only by `check_decoder`
NB14_BEST = {'H1': 20260902, 'H2': 20260901}

RAILED_BAND = 0.05                   # make_nb14 s8: pos < .05 or pos > .95


def sha(p: pathlib.Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def load_run(cell: str, seed: int) -> dict:
    z = np.load(CACHE / f'dds_{cell}_{seed}.npz', allow_pickle=True)
    return {k: z[k] for k in z.files}


# ----------------------------------------------------------------- C0.1 decode
def positions(cell, z) -> pd.DataFrame:
    """make_nb14.py section 8 `positions`, verbatim in arithmetic and column order.

    Position is reported in the TRANSFORMED space the search moved in (log for the
    log-scaled dimensions), because that is where the bound is.
    """
    x, ro, so = CV.unpack(cell, z)
    rows = []

    def row(nm, scope, xv):
        i = CV.NAMES.index(nm)
        pos = float((xv - CV.LO[i]) / (CV.HI[i] - CV.LO[i]))
        return dict(parameter=nm, scope=scope,
                    value=float(CV.inv(np.atleast_1d(xv), CV.IS_LOG[i])[0]),
                    prior=CV.RAW_P0[i], lo=CV.RAW_LO[i], hi=CV.RAW_HI[i], pos=pos,
                    railed='YES' if (pos < RAILED_BAND or pos > 1 - RAILED_BAND) else '')

    for nm in CV.NAMES:
        rows.append(row(nm, 'global', x[CV.NAMES.index(nm)]))
    for nm, vals in (ro or {}).items():
        for k in range(1, len(vals)):
            rows.append(row(nm, f'R{k}', vals[k]))
    for nm, vals in (so or {}).items():
        for k, fam in ((1, 'soil-medium'), (2, 'soil-fine')):
            rows.append(row(nm, fam, vals[k]))
    return pd.DataFrame(rows)


def check_decoder(cell_h2e) -> None:
    """Reproduce the STORED parameters_H1.csv / parameters_H2.csv from their own archives.

    H1's and H2's search vectors have the same 18-dim layout as H2E's (same NREG, same
    bundle geometry for H2), so decoding them with the function above and matching the
    committed CSVs to float tolerance proves this copy of `positions` is nb14's.
    """
    for name in ('H1', 'H2'):
        want = pd.read_csv(OUTD / f'parameters_{name}.csv', keep_default_na=False)
        run = load_run(name, NB14_BEST[name])
        # H1's cell has its own bundle; decoding needs only NREG and the name lists, both
        # of which H2E shares (NREG is read off the topology and is 3 in both bundles).
        got = positions(cell_h2e, run['x'])
        assert list(got.columns) == list(want.columns), f'{name}: column set drifted'
        assert len(got) == len(want), f'{name}: row count {len(got)} vs {len(want)}'
        assert (got.parameter.tolist() == want.parameter.tolist()
                and got.scope.tolist() == want.scope.tolist()), f'{name}: row order drifted'
        for c in ('value', 'prior', 'lo', 'hi', 'pos'):
            d = float(np.abs(got[c].to_numpy() - want[c].to_numpy()).max())
            assert d < 1e-12, f'{name}: column {c} differs by {d:.3e}'
        assert got.railed.tolist() == want.railed.tolist(), f'{name}: railed flags differ'
        print(f'  decoder regression OK: reproduces parameters_{name}.csv '
              f'({len(want)} rows) from dds_{name}_{NB14_BEST[name]}.npz')


# ----------------------------------------------------------------- C0.3 metrics
def fleet(q, obs, mask, ng) -> pd.DataFrame:
    return pd.DataFrame([CV.kge_terms(q[mask][:, j], obs[mask][:, j]) for j in range(ng)])


def clim_bench(cell) -> dict:
    """Day-of-year climatology KGE per period - make_nb14 section 5, `CLIM`."""
    out = {}
    for pn, pm in cell.PERIODS:
        d = pd.DataFrame([CV.kge_terms(cell.QCLIM[pm][:, j], cell.QOBS[pm][:, j])
                          for j in range(cell.NG)])
        out[pn] = float(d.kge.median())
    return out


def metric_rows(cell, q, label, clim) -> tuple[list, dict]:
    """One row per period, columns exactly as metrics_fleet.csv already has them."""
    rows, extra = [], {}
    for pn, pm in cell.PERIODS:
        d = fleet(q, cell.QOBS, pm, cell.NG)
        ks, _ = CV.recession_fleet(q[pm])
        ko = cell.K_OBS[pn]
        ratio_of_medians = float(np.nanmedian(ks) / np.nanmedian(ko))
        with np.errstate(divide='ignore', invalid='ignore'):
            per_gauge = np.where((ks > 0) & (ko > 0), ks / ko, np.nan)
        rows.append(dict(cell=cell.name, config=label, period=pn,
                         kge=float(d.kge.median()), nse=float(d.nse.median()),
                         r=float(d.r.median()), alpha=float(d.alpha.median()),
                         beta=float(d.beta.median()), pbias=float(d.pbias.median()),
                         kge_gt0=int((d.kge > 0).sum()), kge_gt05=int((d.kge > 0.5).sum()),
                         n=int(d.kge.notna().sum()), clim_kge=clim[pn],
                         skill_over_clim=float(d.kge.median()) - clim[pn],
                         rec_ratio=ratio_of_medians))
        # P3 in the journal: the second, inequivalent definition, reported alongside
        extra[pn] = dict(rec_ratio_of_medians=ratio_of_medians,
                         rec_median_of_ratios=float(np.nanmedian(per_gauge)),
                         obs_k_d=float(np.nanmedian(ko)), sim_k_d=float(np.nanmedian(ks)))
    return rows, extra


def prior_vector(cell) -> np.ndarray:
    """nb14 section 7's prior point: every regional/soil extra equals its global parent."""
    x0 = CV.X0.copy()
    return np.concatenate([
        x0,
        np.array([x0[CV.NAMES.index(m)] for m in CV.REG_PARAMS
                  for _ in range(cell.NREG - 1)]),
        np.array([x0[CV.NAMES.index(m)] for m in CV.SOIL_PARAMS for _ in range(2)])])


def main() -> int:
    t0 = time.perf_counter()
    print('=' * 78)
    print('C0 - freeze and report H2E   (docs/31 Stage C0, subtasks C0.1-C0.4)')
    print('=' * 78)

    # ---------------------------------------------------------------- provenance
    eng, cal = REPO / 'src' / 'mgb_hydrology.py', REPO / 'src' / 'calib_v2.py'
    prov = {'engine_sha256': sha(eng), 'calib_v2_sha256': sha(cal)}
    rec = json.loads((OUTD / 'calibration_v2.json').read_text(encoding='utf-8'))
    print(f'\nPROVENANCE  engine  {prov["engine_sha256"][:12]}  '
          f'(nb14 recorded {rec["engine"]["sha256"][:12]})')
    print(f'            calib_v2 {prov["calib_v2_sha256"][:12]}  '
          f'(nb14 recorded {rec["search_code"]["sha256"][:12]})')
    print('            differences are expected: commit 80a7c10 added the FAO-56 option '
          'AFTER nb14\n            ran and BEFORE the H2E search ran; see '
          'docs/agents/journal_c0.md P1.')

    # ---------------------------------------------------------------- the cell
    CV.ensure_cache(CELL_NAME)
    cell = CV.Cell(CELL_NAME, verbose=True)
    print(f'            et_stress={cell.ET_STRESS!r}  theta_crit={cell.THETA_CRIT}')
    assert cell.ET_STRESS == 'fao56' and cell.THETA_CRIT == 0.6, 'H2E cell is not FAO-56'

    run = load_run(CELL_NAME, BEST_SEED)
    pnames, lo, hi, _ = CV.pack_bounds(cell)
    assert [str(s) for s in run['names']] == list(pnames), \
        'stored search-vector layout differs from pack_bounds(cell)'
    f_stored = float(run['f'][0])
    f_arch_max = float(run['arch_f'].max())
    i_best = int(np.argmax(run['arch_f']))
    assert np.allclose(run['arch_x'][i_best], run['x'], rtol=0, atol=0), \
        'stored best x is not the archive argmax'
    print(f'\nARCHIVE     dds_{CELL_NAME}_{BEST_SEED}.npz  budget {int(run["budget"][0])}  '
          f'wall {float(run["wall_s"][0])/60:.1f} min')
    print(f'            f {f_stored!r}   archive max {f_arch_max!r}   '
          f'best eval index {i_best}')
    assert f_stored == f_arch_max, 'stored f is not the archive maximum'
    assert abs(f_stored - F_ARCHIVED) / F_ARCHIVED < 1e-15, \
        f'archive f {f_stored!r} is not the {F_ARCHIVED!r} docs/31 quotes'

    # ------------------------------------------------------------------ C0.1
    print('\n--- C0.1  extract and record the adopted parameter set ' + '-' * 22)
    check_decoder(cell)
    POS = positions(cell, run['x'])
    g = POS[POS.scope == 'global'].set_index('parameter')
    print(POS.to_string(index=False, float_format=lambda v: f'{v:12.6f}'))
    kb, kf, ks_ = float(g.value['k_bas']), float(g.value['k_int_frac']), float(g.value['k_sup'])
    kc = float(g.value['kc_mult'])
    rail_g = POS[(POS.scope == 'global') & (POS.railed == 'YES')]
    rail_a = POS[POS.railed == 'YES']
    print(f'\n  kc_mult {kc:.4f}  (pos {float(g.pos["kc_mult"]):.4f} of its (0.5, 2.0) range)')
    print(f'  railed: {len(rail_g)} of the 10 global, {len(rail_a)} of all {len(POS)} '
          f'-> {", ".join(rail_a.parameter + "@" + rail_a.scope) if len(rail_a) else "none"}')
    print(f'  derived k_int = k_int_frac x k_bas = {kf:.5f} x {kb:.3f} = {kf*kb:.4f} d')
    print(f'  store ordering  k_sup {ks_:.3f} d  <  k_int {kf*kb:.4f} d  <  k_bas {kb:.3f} d : '
          f'{"HOLDS" if ks_ < kf*kb < kb else "VIOLATED (k_int<k_bas holds by construction)"}')
    # C0.1 gate
    assert abs(kc - 1.662) < 5e-4, f'C0.1 gate: kc_mult reads {kc:.5f}, not 1.662'
    kfr = POS[(POS.parameter == 'k_int_frac') & (POS.scope == 'global')].iloc[0]
    assert kfr.railed == 'YES' and kfr.pos < RAILED_BAND, \
        f'C0.1 gate: k_int_frac not flagged railed (pos {kfr.pos:.4f})'
    print(f'  C0.1 GATE PASS: kc_mult reads 1.662; k_int_frac railed=YES at its '
          f'{CV.RAW_LO[CV.NAMES.index("k_int_frac")]} floor (pos {kfr.pos:.5f})')

    # ------------------------------------------------------------------ C0.2
    print('\n--- C0.2  REPRODUCTION GATE (blocks everything else) ' + '-' * 24)
    x, ro, so = CV.unpack(cell, run['x'])
    tg = time.perf_counter()
    f_new, xtra = cell.F_of(x, ro, so)
    rel = abs(f_new - f_stored) / abs(f_stored)
    print(f'  archived  F = {f_stored!r}')
    print(f'  recomputed F = {f_new!r}   ({time.perf_counter()-tg:.1f} s)')
    print(f'  absolute difference {abs(f_new - f_stored):.3e}   relative {rel:.3e}   '
          f'bar <= {GATE_REL:.0e}')
    if not (rel <= GATE_REL):
        print('\n  C0.2 GATE FAIL - the environment has drifted. STOPPING: docs/31 Stage C0 '
              'makes\n  this gate block every other subtask, and nothing downstream is '
              'trustworthy.')
        return 1
    print(f'  C0.2 GATE PASS (relative {rel:.3e} <= {GATE_REL:.0e})')
    # the archive also stores the per-gauge terms of the best evaluation; check them too,
    # because F is a scalar and a scalar can match by coincidence in ways 63 terms cannot.
    for k, arr in (('k1', 'arch_k1'), ('k2', 'arch_k2'), ('k_sim', 'arch_ks')):
        a, b = np.asarray(run[arr][i_best], np.float32), np.asarray(xtra[k], np.float32)
        m = np.isfinite(a) | np.isfinite(b)
        same_nan = np.array_equal(np.isfinite(a), np.isfinite(b))
        d = float(np.nanmax(np.abs(a[m] - b[m]))) if m.any() else 0.0
        print(f'  per-gauge {k:5s}: max |diff| {d:.3e} over {int(m.sum())} gauges, '
              f'NaN pattern {"identical" if same_nan else "DIFFERS"}')
        assert same_nan and d == 0.0, f'per-gauge {k} does not reproduce bit-for-bit'
    print('  all 3 x 63 stored per-gauge terms reproduce bit-for-bit')

    # ------------------------------------------------------------------ C0.3
    print('\n--- C0.3  full simulation + per-period metrics ' + '-' * 31)
    clim = clim_bench(cell)
    z_h2 = pd.read_csv(OUTD / 'metrics_fleet.csv')
    for pn, v in clim.items():
        h2 = z_h2[(z_h2.cell == 'H2') & (z_h2.config == 'fit') & (z_h2.period == pn)]
        if len(h2):
            d = abs(v - float(h2.clim_kge.iloc[0]))
            assert d < 1e-12, f'climatology benchmark drifted vs H2 at {pn}: {d:.3e}'
    print(f'  climatology benchmark reproduces H2\'s stored clim_kge on all '
          f'{len(cell.PERIODS)} periods (same bundle, same gauges)')

    Q, ROWS, EXTRA = {}, [], {}
    for label, zvec in (('prior', prior_vector(cell)), ('fit', run['x'])):
        xx, rr, ss = CV.unpack(cell, zvec)
        res, _ = cell.run_full(xx, rr, ss)
        Q[label] = res.q_m3s.astype(np.float64)
        bal = res.balance
        print(f'  {label:5s}: {res.wall_time_s:6.1f} s  backend {res.routing_backend}  '
              f'resid_rel {bal["residual_relative"]:.3e}  RC {bal["runoff_coefficient"]:.4f}  '
              f'clip {bal["clip_volume_mm_km2"]:.1f}')
        assert bal['residual_relative'] < 1e-15, \
            f'C0.3 gate: {label} mass-balance residual {bal["residual_relative"]:.3e} >= 1e-15'
        assert bal['clip_volume_mm_km2'] == 0.0, f'{label}: the negative-W guard fired'
        rows, extra = metric_rows(cell, Q[label], label, clim)
        ROWS += rows
        EXTRA[label] = extra
        if label == 'fit':
            BAL_FIT = dict(bal)
    print('  C0.3 GATE (a) PASS: mass-balance residual < 1e-15 relative at both sets')

    SUM = pd.DataFrame(ROWS)
    print()
    print(SUM.drop(columns=['cell']).to_string(index=False,
                                               float_format=lambda v: f'{v:9.4f}'))
    print('\n  recession, both definitions (journal P3), fitted set:')
    print(f'    {"period":<20s} {"obs k_d":>8s} {"sim k_d":>8s} '
          f'{"ratio-of-medians":>17s} {"median-of-ratios":>17s}')
    bad = []
    for pn, e in EXTRA['fit'].items():
        print(f'    {pn:<20s} {e["obs_k_d"]:8.3f} {e["sim_k_d"]:8.3f} '
              f'{e["rec_ratio_of_medians"]:17.4f} {e["rec_median_of_ratios"]:17.4f}')
        for key in ('rec_ratio_of_medians', 'rec_median_of_ratios'):
            if not (1 / 1.5 <= e[key] <= 1.5):
                bad.append(f'{pn}/{key}={e[key]:.4f}')
    assert not bad, f'C0.3 gate: recession ratio outside [1/1.5, 1.5] at {bad}'
    print('  C0.3 GATE (b) PASS: every period within [1/1.5, 1.5] on BOTH definitions')

    # ------------------------------------------------------------------ write
    np.savez_compressed(
        OUTD / f'q_gauge_{CELL_NAME}.npz',
        dates=cell.D_SC.to_numpy().astype('datetime64[D]'), gauge_code=cell.GC,
        gauge_upstream_area_km2=cell.GUP, region=cell.REG[cell.GMIDX[cell.JP]],
        q_obs_m3s=cell.QOBS.astype(np.float32),
        q_sim_prior_m3s=Q['prior'].astype(np.float32),
        q_sim_fit_m3s=Q['fit'].astype(np.float32),
        q_clim_m3s=cell.QCLIM.astype(np.float32))
    POS.to_csv(OUTD / f'parameters_{CELL_NAME}.csv', index=False)

    # Appended as TEXT, not via a pandas read->write round trip.  Measured 2026-08-10:
    # `pd.read_csv(...).to_csv(...)` re-emits the pre-existing H1/H2/ref floats one digit
    # short (0.08329265113146145 -> 0.0832926511314614), and the two strings do NOT parse
    # to the same float64 (3 ULP apart).  Those rows are quoted in docs/21 and docs/26, so
    # rewriting them at all is unacceptable; keeping their bytes verbatim is the only way
    # to guarantee this step adds rows and changes nothing.
    mf_path = OUTD / 'metrics_fleet.csv'
    lines = mf_path.read_text(encoding='utf-8').splitlines()
    header, body = lines[0], [ln for ln in lines[1:] if ln.strip()]
    cols = header.split(',')
    assert cols == list(SUM.columns), f'metrics_fleet column set drifted: {cols}'
    kept = [ln for ln in body if not ln.startswith(f'{CELL_NAME},')]
    n_drop = len(body) - len(kept)                     # idempotent re-run

    def fmt(v):
        if isinstance(v, str):
            return v
        if isinstance(v, (bool, np.bool_)) or isinstance(v, (int, np.integer)):
            return str(int(v))
        return repr(float(v))                          # shortest round-trippable

    new = [','.join(fmt(r[c]) for c in cols) for _, r in SUM.iterrows()]
    mf_path.write_text('\n'.join([header] + kept + new) + '\n', encoding='utf-8')
    print(f'\n  metrics_fleet.csv: {len(body)} rows -> {len(kept) + len(new)} '
          f'({n_drop} stale {CELL_NAME} rows replaced, {len(new)} appended; '
          f'{len(kept)} pre-existing rows kept byte-for-byte)')
    # prove the pre-existing rows were not touched
    reread = mf_path.read_text(encoding='utf-8').splitlines()
    assert reread[1:1 + len(kept)] == kept, 'pre-existing metrics_fleet rows were altered'

    # ------------------------------------------------------------------ C0.4
    print('\n--- C0.4  the two tables every later stage quotes ' + '-' * 28)
    mf = pd.read_csv(OUTD / 'metrics_fleet.csv')
    key = [('ref', 'ConfigB', 'Config B (v1, old objective)'),
           ('H1', 'fit', 'H1  v1 forcing + new objective'),
           ('H2', 'fit', 'H2  v2 forcing + new objective'),
           ('H2E', 'fit', 'H2E v2 + new objective + FAO-56 ET')]
    cols = ['kge', 'nse', 'r', 'alpha', 'beta', 'pbias', 'rec_ratio',
            'skill_over_clim', 'n']

    def railed_counts(c):
        """Both denominators, deliberately.  Reporting only one is what produced the
        docs/24-vs-docs/26 "3 of 10 vs 2" discrepancy (docs/31 known-open #1, resolved in
        review_2026-08-10_docs31.md s3: one 18-dim vector, two denominators).  Config B
        has no parameters_*.csv in this bundle; nb14 section 8 records its count as 3 of
        10 global (kc_mult, k_int, fint), which is the figure carried here."""
        if c == 'ref':
            return 3, np.nan
        t = pd.read_csv(OUTD / f'parameters_{c}.csv', keep_default_na=False)
        return (int((t[t.scope == 'global'].railed == 'YES').sum()),
                int((t.railed == 'YES').sum()))

    ta = []
    for c, cf, lab in key:
        row = mf[(mf.cell == c) & (mf.config == cf) & (mf.period == 'VAL all')]
        assert len(row) == 1, f'VAL all row missing for {c}/{cf}'
        d = {'attempt': lab}
        d.update({k: float(row[k].iloc[0]) for k in cols})
        d['railed_global_of_10'], d['railed_all_of_18'] = railed_counts(c)
        ta.append(d)
    TA = pd.DataFrame(ta)
    print('\n(a) the four-attempt history, VAL-all row')
    print(TA.to_string(index=False, float_format=lambda v: f'{v:9.4f}'))

    tb = []
    for pn in ('VAL La Nina 11', 'VAL El Nino 15-16'):
        row = mf[(mf.cell == 'H2E') & (mf.config == 'fit') & (mf.period == pn)].iloc[0]
        tb.append(dict(period=pn, kge=float(row.kge), clim_kge=float(row.clim_kge),
                       skill_over_clim=float(row.skill_over_clim), r=float(row.r),
                       alpha=float(row.alpha), beta=float(row.beta),
                       pbias=float(row.pbias), rec_ratio=float(row.rec_ratio),
                       n=int(row.n)))
    TB = pd.DataFrame(tb)
    TB.loc[len(TB)] = dict(period='asymmetry (La Nina - El Nino)',
                           **{c: (float(TB[c].iloc[0]) - float(TB[c].iloc[1]))
                              for c in TB.columns if c != 'period'})
    print('\n(b) ENSO asymmetry restated for H2E (the number C5 inherits)')
    print(TB.to_string(index=False, float_format=lambda v: f'{v:9.4f}'))

    rep = {
        'stage': 'C0', 'cell': CELL_NAME, 'best_seed': BEST_SEED,
        'generated_by': 'src/report_h2e.py',
        'provenance': prov,
        'engine_blob_note': 'commit 80a7c10 (2026-08-03 20:34) is the last commit touching '
                            'src/mgb_hydrology.py and src/calib_v2.py; it predates the H2E '
                            'search (2026-08-04 23:04 -> 2026-08-05 02:26), so the files on '
                            'disk are the ones the search ran.',
        'cell_config': {'bundle': cell.bundle, 'et_stress': cell.ET_STRESS,
                        'theta_crit': cell.THETA_CRIT,
                        'scored': [str(cell.D_SC[0].date()), str(cell.D_SC[-1].date())],
                        'scored_days': int(len(cell.D_SC)), 'n_gauges': int(cell.NG)},
        'C0_2_reproduction_gate': {'archived_F': f_stored, 'recomputed_F': f_new,
                                   'relative_difference': rel, 'bar': GATE_REL,
                                   'pass': True,
                                   'per_gauge_terms_bit_identical': True},
        'C0_1_parameters': {'kc_mult': kc, 'k_bas_d': kb, 'k_int_frac': kf,
                            'k_int_derived_d': kf * kb, 'k_sup_d': ks_,
                            'railed_global': int(len(rail_g)), 'railed_all': int(len(rail_a)),
                            'railed': (rail_a.parameter + '@' + rail_a.scope).tolist()},
        'C0_3_balance_fit': BAL_FIT,
        'C0_3_recession_both_definitions': EXTRA['fit'],
        'C0_4a_four_attempt_history_VAL_all': TA.to_dict(orient='records'),
        'C0_4b_enso_asymmetry_H2E': TB.to_dict(orient='records'),
    }
    (OUTD / 'report_H2E.json').write_text(json.dumps(rep, indent=1, default=str),
                                          encoding='utf-8')

    # round trip - nothing is trusted to have been written correctly
    r2 = json.loads((OUTD / 'report_H2E.json').read_text(encoding='utf-8'))
    p2 = pd.read_csv(OUTD / f'parameters_{CELL_NAME}.csv', keep_default_na=False)
    q2 = np.load(OUTD / f'q_gauge_{CELL_NAME}.npz', allow_pickle=True)
    m2 = pd.read_csv(OUTD / 'metrics_fleet.csv')
    print(f'\nROUND TRIP  report_H2E.json F {r2["C0_2_reproduction_gate"]["recomputed_F"]!r}')
    print(f'            parameters_{CELL_NAME}.csv {len(p2)} rows, kc_mult '
          f'{float(p2[(p2.parameter=="kc_mult")&(p2.scope=="global")].value.iloc[0]):.6f}')
    print(f'            q_gauge_{CELL_NAME}.npz keys {sorted(q2.files)}')
    print(f'            q_sim_fit_m3s {q2["q_sim_fit_m3s"].shape} vs QOBS '
          f'{cell.QOBS.shape}; max |reload - memory| '
          f'{float(np.abs(q2["q_sim_fit_m3s"] - Q["fit"].astype(np.float32)).max()):.3e}')
    print(f'            metrics_fleet.csv {len(m2)} rows, H2E rows '
          f'{int((m2.cell == CELL_NAME).sum())}')
    assert abs(float(m2[(m2.cell == CELL_NAME) & (m2.config == 'fit')
                       & (m2.period == 'VAL all')].kge.iloc[0])
               - float(SUM[(SUM.config == 'fit') & (SUM.period == 'VAL all')].kge.iloc[0])) < 1e-9
    assert q2['q_sim_fit_m3s'].shape == cell.QOBS.shape

    print(f'\nC0.1-C0.4 COMPLETE in {(time.perf_counter()-t0)/60:.1f} min')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
